In [29]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer



In [30]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

In [31]:
# Selecting the target column
X = df.drop(columns = ["Survived"])
y = df["Survived"]

In [32]:
# Identifying the feature type
numerical_feature = X.select_dtypes(include = 'number').columns
categorical_feature = X.select_dtypes(include = 'object').columns

In [33]:
# Imputing missing values and scaling for numerical features
numeric_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy = 'median')),
    ('scaling',StandardScaler())
])

In [34]:
# Imputing missing values and scaling for categorical features
categorical_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy = 'most_frequent')),
    ('encoder',OneHotEncoder(handle_unknown = 'ignore'))
    
])

In [82]:
# Columntransforming
transformer = ColumnTransformer([
    ('numeric_pipe',numeric_pipeline,numerical_feature),
    ('categoric_pipe',categorical_pipeline,categorical_feature)
])

In [73]:
from sklearn.linear_model import LinearRegression
lr_pipeline = Pipeline([
    ('preprosser',transformer),
    ('model',LinearRegression())
])



In [74]:
from sklearn.model_selection import cross_val_score

# performing cross_validation on LinearRegression
scores = cross_val_score(
    lr_pipeline,
    X,
    y,
    cv=5,
    scoring = 'r2'
)



In [75]:
print(scores)
print(scores.mean())
scores.std()

[0.40115761 0.38186991 0.45945536 0.39859019 0.49493363]
0.4272013408821529


np.float64(0.042848096885564436)

In [76]:
from sklearn.tree import DecisionTreeRegressor


dtr_pipeline = Pipeline([
    ('preprosser',transformer),
    ('model',DecisionTreeRegressor())
])

In [77]:
# performing cross_validation on DecisionTreeRefressor
scores = cross_val_score(
    dtr_pipeline,
    X,
    y,
    cv=5,
    scoring = 'r2'
)



In [78]:
print(scores)
print(scores.mean())
scores.std()

[0.08983051 0.1579082  0.26632097 0.16037736 0.43492063]
0.22187153314500901


np.float64(0.12055981606539555)

In [79]:
from sklearn.ensemble import RandomForestRegressor
Rfr_pipeline = Pipeline([
    ('preprosser',transformer),
    ('model',RandomForestRegressor())
])


 

In [80]:
# performing cross_validation on RandomForestRegressor
scores = cross_val_score(
    Rfr_pipeline,
    X,
    y,
    cv=5,
    scoring = 'r2'
)


In [81]:
print(scores)
print(scores.mean())
scores.std()

[0.38271041 0.38565079 0.46651358 0.34162856 0.55770501]
0.42684166911293475


np.float64(0.07694752030387468)